name: Selenium IDE CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable || true
          wget -q "https://chromedriver.storage.googleapis.com/137.0.7151.119/chromedriver_linux64.zip" || { echo "Failed to download ChromeDriver"; exit 1; }
          unzip chromedriver_linux64.zip || { echo "Failed to unzip ChromeDriver"; exit 1; }
          sudo mv chromedriver /usr/local/bin/ || { echo "Failed to move ChromeDriver"; exit 1; }
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./SeleniumIDE
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./SeleniumIDE
      